### ISSUE TITLE
Installing dependencies fails

### ISSUE THREAD

**Issue by paleiadevelopment** [pzim-devdata/tahoma#1]
Hi!

When I try to install the dependencies (Win 10 Pro), I get this error:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Scripts\pip.exe\__main__.py", line 2, in <module>
  File "F:\Portable\tahoma\re.py", line 125, in <module>
    import sre_compile
  File "C:\Users\Me\AppData\Local\Programs\Python\Python311\Lib\sre_compile.py", line 6, in <module>
    from re import _compiler as _
ImportError: cannot import name '_compiler' from partially initialized module 're' (most likely due to a circular import) (F:\Portable\tahoma\re.py)

Does this require Linux, maybe?

**Comment by pzim-devdata** [comment]
The error is the last line : `ImportError: cannot import name '_compiler' from partially initialized module 're'`
That's mean python can't import re, perhaps because it's already in the folder ("F:\Portable\tahoma\re.py")
Did you tried : `python3 -m pip install regex` ?
Did you also tried with the pip install of tahoma ? : https://pypi.org/project/tahoma/#description
Do you have the last version of Python3 ?
re is included in the portable version (re.py), did you tried to remove re.py from : "F:\Portable\tahoma\re.py" ?

**Comment by pzim-devdata** [comment]
Did you tried to reinstall python3 from the Windows Store ?
I suggest you to uninstall your version of Python and to install it from the Windows Store. It's working perfectly with me on Windows 11

**Comment by paleiadevelopment** [comment]
Fully removing all existing Python 3 versions and then re-installing from the store worked, thanks a lot!
