### ISSUE TITLE
Device NOT Controlled by ahoma yet

### ISSUE THREAD

**Issue by Commando2007** [pzim-devdata/tahoma#11]
I am testing the software but my device cannot be controlled.

I hit

TOLDO,io://2078-0794-8318/12516575,PergolaHorizontalAwning,Pergola,io:PergolaRailGuidedAwningIOComponent
TOLDO,io://2078-0794-8318/12516575,PergolaHorizontalAwning,Pergola,io:PergolaRailGuidedAwningIOComponent
Device 'TOLDO' NOT controlled by tahoma yet
States for TOLDO added to : /home/pi/.local/lib/python3.9/site-packages/tahoma/temp/states.txt

the state is real.

thanks in advance

**Comment by Commando2007** [comment]
Gracias igualmente, 
He variado el get_devices_url.py añadiendo mi Pergola , ahora ya aparce como reconocido y controlable.
Ya he probado funcionamiento,todo correcto.

Ota pregunta 👍 
en states.txt  figura el estado del dispositivo ( en este caso open o closed) pero hay alguna lista de variables de somfy para acceder a otros valores ( como el % ) ...... ?

gracias de nuevo .

Great job !!

**Comment by pzim-devdata** [comment]
Hello Commando2007,

I will add the pergola category to tahoma thanks to your feedback.

It will be like this: `tahoma open pergola garden`

I will push a new version of tahoma with the pergola category.
I will do it next week because I am very busy.

If you have already created the pergola category, could you please send me your code?

Unfortunately, it is not possible to get the percentage of the opening level. It is simply to open or close, but you can close the pergola to a specific percentage with a numeric value like ACTION: `tahoma 25 pergola garden`: this will close the pergola named "garden" to 25%.

Thanks for the encouragement,
pzim-devdata

#####################

Hola Commando2007,

Agregaré la categoría pérgola a tahoma gracias a tu feedback.

Será así: `tahoma open pergola garden`

Voy a lanzar una nueva versión de tahoma con la categoría pérgola.
Lo haré la semana que viene porque estoy muy ocupado.

Si ya creaste la categoría pérgola, ¿podrías enviarme tu código?

Lamentablemente, no es posible obtener el porcentaje del nivel de apertura. Es simplemente para abrir o cerrar, pero puedes cerrar la pérgola a un porcentaje específico con un valor numérico como ACTION: `tahoma 25 pergola garden`: esto cerrará la pérgola llamada "garden" al 25%.

Gracias por el aliento,
pzim-devdata

**Comment by Commando2007** [comment]
Perdon por tardar en responder,tengo poco tiempo.
Solo añadi en get_devices_url.py la linea:
" if "Shutter" in device.widget or "PergolaHorizontalAwning" in device.widget:
                    f3.write(device.label+","+device.id+","+device.widget+"\n")

                elif "Shutter" in device.widget or "PositionableTiltedScreen" in device.widget: "
el primer if es el mio y el tuyo original pasa a ser el primer elif,de esta forma el dispositivo es reconocido y funciona.

Ahora quiero hacerte una pregunta:
Mi dispositivo es IO  ( no es RTS ) pero la accion STOP no funciona,arroja errores:
{'errorCode': 'UNSPECIFIED_ERROR', 'error': 'Managed action group is invalid : Too many command parameters : expected at most 0 but got 1'}, he visto por encima el codigo y en principio no veo "nada raro" .

 Enfin no se´si tienes alguna pista de como solucionarlo,porque otra opcion seria que se  comportara como el mando RF del motor ( haces el stop con el boton MY,sin configurar como posicion favorita),pero la app de SOMFY solo permite configurar ese boton u orden como posicion favorita,no aparece la opción de configutarlo como stop.

Saludos y gracias por adelantado.

########################################################################################

Sorry for the delay in responding, I have little time.
I just added the line in get_devices_url.py:
" if "Shutter" in device.widget or "PergolaHorizontalAwning" in device.widget:
f3.write(device.label+","+device.id+","+device.widget+"\n")

            elif "Shutter" in device.widget or "PositionableTiltedScreen" in device.widget: "
The first if is mine and your original becomes the first elif, this way the device is recognized and works.

Now I want to ask you a question:
My device is IO (it is not RTS) but the STOP action does not work, it throws errors:
{'errorCode': 'UNSPECIFIED_ERROR', 'error': 'Managed action group is invalid : Too many command parameters : expected at most 0 but got 1'}, I have looked at the code and in principle I don't see "anything strange" .

Anyway, I don't know if you have any clue on how to solve it, because another option would be that it behaves like the RF control of the engine (you stop with the MY button, without configuring it as a favorite position), but the SOMFY app only allows you to configure that button or order as a favorite position, the option to configure it as a stop does not appear.

Greetings and thanks in advance.

**Comment by pzim-devdata** [comment]
Hello,

I'm sorry I had no time to create a Pergola category yet.

Could you please try with this two files :
[tahoma_pergola.zip](https://github.com/user-attachments/files/17269179/tahoma_pergola.zip)
and tell me if all is ok ?

Don't forget to run `tahoma --getlist` after replacing this 2 files to the tahoma folder.

Could you also try `tahoma -ln` `tahoma -la` and `tahoma -lc`  and tell me if all is ok ?

Then try : `tahoma open pergola toldo wait for 7 close pergola toldo wait for 2 stop pergola toldo` and tell me if it's ok ?
Could you also try : `tahoma open pergola toldo wait for 7 close pergola toldo wait for 2 cancel last action`  and see if the pergola stop?
