### ISSUE TITLE
Device name resolution fails with multiple common words.

### ISSUE THREAD

**Issue by paleiadevelopment** [pzim-devdata/tahoma#3]
I have a lot of devices like
Floor Room, for example "Ground Kitchen".
So there will also be
1st Kitchen
Ground Bath
1st Bath
etc...

Tahoma doesn't let me call up these names, as there is no word that occurs only in one of them.
Would it be possible to allow for quote strings to be used in a future version?
Like 
open sunscreen "1st Kitchen Left Atrium" (where 1st Kitchen Left Atrium is the name of the device registered with Tahoma's servers?

best

Tobias

**Comment by pzim-devdata** [comment]
Yes I could make it like I have made it for sensors. 
I have made it just for sensors, because we can ask for many sensors in one time with just a part of the name and a specific sensor with [""] and because we can have many sensors in the same room.
I will try to make it for other devices(not only sensors) and let you know, but for now, there is always a solution to find the unic word. For instance : 
1st Kitchen --> kitchen
Ground Bath --> ground
1st Bath -- bath.
I will make it and give you a zip file to test and I wil publish it if it's working. I think next week. If you have any other suggestions let me know now, because when I edit the code the longest work is to publish on github and pypi because I have to modify the code for each and it's the longest part. Excuse me for my english ;-)

**Comment by paleiadevelopment** [comment]
That would be awesome!

I'm currently working on a little UI tool for Windows to control my sunscreens - this "issue" is the only problem I have right now :)
If I get it done, I'll host it on Github, maybe it will be useful for others, too.

**Comment by pzim-devdata** [comment]
Hello, could try this zip file and let me know if you find a bug ?

Thanks
[tahoma-main.zip](https://github.com/pzim-devdata/tahoma/files/11675430/tahoma-main.zip)

**Comment by paleiadevelopment** [comment]
It works great, thanks so much!!

One small thing:
If the name of the device is also part of the name of other devices, I need to write 'Name'. If it is not, then "Name".
Would it be possible to make this consistent?

Also a small typo: "Choose a UNIC part" should be UNIQUE.

See the print from console below.


F:\Portable Applications\tahoma>python3 tahoma.py close sunscreen **"Erker"**
There is more than one match. The <NAME> you gave is not exact. Choose a UNIC part of word from this results as <NAME> argument or use [''] with the full name : ['EG Erker links', 'EG Erker rechts ', 'EG Erker mitte', 'Erker']
See tahoma --list-names for help.

F:\Portable Applications\tahoma>python3 tahoma.py close sunscreen **'Erker'**
Output action : CLOSE sunscreen Erker
with url : io://2026-9407-8819/5862570

F:\Portable Applications\tahoma>python3 tahoma.py close sunscreen **"Kueche links"**
Output action : CLOSE sunscreen Kueche links
with url : io://2026-9407-8819/5642491

F:\Portable Applications\tahoma>python3 tahoma.py close sunscreen **'Kueche links'**
There is no match. The <NAME> you gave is not exact. Did you mean : ['EG Erker links', 'EG Erker rechts ', 'Schlafzimmer ', 'EG Erker mitte', 'Balkon', 'Kueche vorne', 'Studio', 'Kueche links', 'Erker', 'Wohnzimmer', 'Bad', 'Treppenhaus'] ? Choose a UNIC part of word from this results as <NAME> argument or use [''] with the full name
If you don't find your device in this results try tahoma --getlist
See tahoma --list-names for help.

**Comment by pzim-devdata** [comment]
OK I will correct this on next update. Thanks
