### ISSUE TITLE
Erreur ssl 

### ISSUE THREAD

**Issue by kitebuggylux** [pzim-devdata/tahoma#9]
Bonjour

J'essaye de lancer une commande, mais je ne recois qu'un message d'erreur:
I try to launch a command, but I receive an error message:

alex@debian:~$ tahoma --password 'secret ' close shutter 'Kummer Alex'
Your PASSWORD has been taken into account
Output action : CLOSE shutter Kummer Alex
Cannot connect to host gateway-2072-4064-5123.local:8443 ssl:<ssl.SSLContext object at 0x7ff9b7342210> [Name or service not known]

Couldn't connect, trying to get a new token or a new gateway_id...
Unsupported value 128 has been returned for <enum 'GatewayType'>
Succes, new token available and found the gateway_id
If you also use the local API with Homebridge or Home Assistant, you will need to use this new token: 23460594e4456234bd76
Your token will be store there: 
/home/alex/.local/pipx/venvs/tahoma/lib/python3.11/site-packages/tahoma/temp/token.txt
Tahoma will use this PIN number of the gateway : 2072-4064-5123
The PIN number of your gateway will be store there: 
/home/alex/.local/pipx/venvs/tahoma/lib/python3.11/site-packages/tahoma/temp/gateway_id.txt
Cannot connect to host gateway-2072-4064-5123.local:8443 ssl:<ssl.SSLContext object at 0x7ff9b7342690> [Name or service not known]
sh: 1: notify-send: not found

When I try a ping to gateway-2072-4064-5123, I've got positive answers. The gateway is reachable.

What must I do?

Thanx

Al

**Comment by pzim-devdata** [comment]
Hello,
Thank you for your message.
It’s because you are using the local API as main parameter (tahoma -c).
Try this : add --remote

***@***.***:~$ tahoma --password 'secret ' close shutter 'Kummer Alex' --remote

Did you configured tahoma with tahoma -c ?
Did you provided a username (mail address) ?
Perhaps your shutter did not work with the local api of tahoma.
Did you created a Somfy developer’s account for using the local API ?h

**Comment by pzim-devdata** [comment]
Hello,
Thank you for your message.
It’s because you are using the local API as main parameter (tahoma -c).
Try to add this at the end of your comman :  `--remote`

`tahoma --password 'secret ' close shutter 'Kummer Alex' --remote`

Did you configured tahoma with `tahoma -c` ?
Did you provided a username (mail address) `--username mail@address` ?
Perhaps your shutter did not work with the local api of tahoma.
Did you created a Somfy developer’s account for using the local API ?

Be careful to your message, there is the gateway-id and the token inside.

Let me know if `--remote` works ;-)

**Comment by kitebuggylux** [comment]
thanks --remote was the missing parameter.

_Be careful to your message, there is the gateway-id and the token inside._
I already changed this values before posting. 
_sh: 1: notify-send: not found_
what package must I install (in Debian) to solve this?

Al

**Comment by pzim-devdata** [comment]
sudo apt install libnotify-bin

Try after after in terminal this command:
notify-send ‘tahoma’ ´if your device is not compatible with the local API try to use the cloud API by default : Execute tahoma -c to use the cloud API by default as it the --remote parameter will be useless’

**Comment by pzim-devdata** [comment]
sudo apt install libnotify-bin

Try after after in terminal this command:
`notify-send "tahoma" "if your device is not compatible with the local API try to use the cloud API by default : Execute tahoma -c to use the cloud API by default as it the --remote parameter will be useless"`
